# https://doc.qt.io/qt-6/macos.html
c_stdlib_version:          # [osx]
  - '11.0'                 # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - '12.3'                 # [osx]

qt:
  - 5
  - 6
c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
