{% set version = "0.7.4" %}

package:
  name: qt6molecularnetwork
  version: {{ version }}

source:
  url: https://github.com/metgem/QtMolecularNetwork/archive/v{{ version }}.tar.gz
  sha256: 728e03771039c86026e29ffcdaa5bc8c6f81d86a72b99b22ba57d441b5427bcc

build:
  number: 1
  skip: true  # [py<39]
  run_exports:
    - {{ pin_subpackage('qt6molecularnetwork', max_pin='x.x.x') }}
  ignore_run_exports_from:
    # Just used to satisfy CMake; not used in shared library
    - cairo
    - freetype
    - libboost-devel

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make                                    # [not win]
    - {{ cdt('mesa-libgl-devel') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}           # [linux]
    - {{ cdt('libglvnd-opengl') }}            # [linux]
    - {{ cdt('libselinux') }}                 # [linux]
    - {{ cdt('libxdamage') }}                 # [linux]
    - {{ cdt('libxxf86vm') }}                 # [linux]
    - {{ cdt('libxext') }}                    # [linux]
  host:
    - cairo
    - freetype
    - libboost-devel
    - eigen
    - qt6-main
    - {{ pin_compatible('rdkit', max_pin='x.x') }}
    - {{ pin_compatible('rdkit-dev', max_pin='x.x') }}      # [win]
    - versioneer
    - tomli              # [py<311]
  run:
    - {{ pin_compatible('rdkit', max_pin='x.x') }}


test:
  commands:
    - if not exist %LIBRARY_BIN%\qt6molecularnetwork.dll exit 1                                     # [win]
    - if not exist %LIBRARY_INC%\qt6molecularnetwork\node.h exit 1                                  # [win]
    - if not exist %LIBRARY_LIB%\cmake\qt6molecularnetwork\qt6molecularnetworkConfig.cmake exit 1   # [win]
    - test -f $PREFIX/lib/libqt6molecularnetwork${SHLIB_EXT}                                        # [unix]
    - test -f $PREFIX/include/qt6molecularnetwork/node.h                                            # [unix]
    - test -f $PREFIX/lib/cmake/qt6molecularnetwork/qt6molecularnetworkConfig.cmake                 # [unix]

outputs:
  - name: qt6molecularnetwork
  - name: pyside6mn
    script: build-python.sh  # [unix]
    script: bld-python.bat  # [win]
    build:
      ignore_run_exports_from:
      # Just used for shiboken/pyside2 not used for python module
        - clangdev  # [not osx]
        - libcxx    # [not osx]
        - libboost-devel
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - clangdev
        - cmake
        - make                                # [not win]
        - libcxx                              # [linux]
        - {{ cdt('mesa-libgl-devel') }}       # [linux]
        - {{ cdt('mesa-dri-drivers') }}       # [linux]
        - {{ cdt('libselinux') }}             # [linux]
        - {{ cdt('libxdamage') }}             # [linux]
        - {{ cdt('libxxf86vm') }}             # [linux]
        - {{ cdt('libxext') }}                # [linux]
      host:
        - {{ pin_subpackage('qt6molecularnetwork', exact=True) }}
        - {{ pin_compatible('rdkit-dev', max_pin='x.x') }}  # [win]
        - {{ pin_compatible('rdkit', max_pin='x.x') }}
        - python
        - cmake-build-extension
        - {{ pin_compatible('qt6-main', max_pin='x.x') }}
        - pyside6
        - versioneer
        - eigen
        - libboost-devel
        - pip
        - setuptools
        - cairo
        - freetype
      run:
        - python
        - {{ pin_subpackage('qt6molecularnetwork', exact=True) }}
        - {{ pin_compatible('rdkit', max_pin='x.x') }}
        - pywin32                             # [win]
        - pyside6
        - tinycss2
    test:
      imports:
        - PySide6MolecularNetwork
        - PySide6MolecularNetwork.qmn

about:
  home: https://github.com/metgem/QtMolecularNetwork
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: 'LICENSE'
  summary: 'Widgets used for visualisation of graph in MetGem'
  description: 'Widgets used for visualisation of graph in `MetGem`'
  dev_url: 'https://github.com/metgem/QtMolecularNetwork'

extra:
  recipe-maintainers:
    - n-elie
